encoder_name: resnet_50 # either clip_base, clip_large, resnet_50, resnet_18
unfreeze: 0
epochs: 5
lr: 0.001 # clip_base: 0.001, clip_large: 0.0001, resnet_50: 0.001

image_path: data/stairs_dataset_20231219/stairs_dataset
gt_path: data/stairs_dataset_20231219/stairs_dataset_annotation.csv
batch_size: 16
val_size: 0.15
test_size: None
seed: 42 

run_name: DATETIME_enc:resnet50_batch:16
experiment_name: clip-classifier
ckp_path: checkpoints/DATETIME
best_ckp_path: checkpoints/20231221-161459/epoch=4.ckpt # DGX

compute: gpu
devices: 0

scheduler:
  mode: min
  factor: 0.1
  patience: 10
  threshold: 0.0001
  threshold_mode: rel